return {
	cmd = { "harper-ls", "--stdio" },
	filetypes = {
		"c",
		"cpp",
		"cs",
		"gitcommit",
		"go",
		"html",
		"java",
		"javascript",
		"lua",
		"markdown",
		"nix",
		"python",
		"ruby",
		"rust",
		"swift",
		"toml",
		"typescript",
		"typescriptreact",
		"haskell",
		"cmake",
		"typst",
		"php",
		"dart",
	},
	root_markers = { ".git" },

	settings = {
		["harper-ls"] = {
			userDictPath = "~/.config/harper/dict.txt",
			fileDictPath = "~/.config/harper/",

			diagnosticSeverity = "hint",
			isolateEnglish = true,

			linters = {
				spell_check = true,
				spelled_numbers = false,
				an_a = true,
				sentence_capitalization = false,
				unclosed_quotes = true,
				wrong_quotes = false,
				long_sentences = true,
				repeated_words = true,
				spaces = true,
				matcher = true,
				correct_number_suffix = true,
				number_suffix_capitalization = true,
				multiple_sequential_pronouns = true,
				linking_verbs = false,
				avoid_curses = true,
				terminating_conjunctions = true,
			},
			codeActions = {
				forceStable = true,
			},
		},
	},
}
